### PR TITLE
fix: replace `cp --parents` with bash script for macOS compatibility

### LINKED ISSUE #246: Failure on MacOS since cp does not support --parents
Hi team
tox-ansible fails on MacOS with an error for cp not supporting `--parents`.

This line:
https://github.com/ansible/tox-ansible/blob/d9c7d08dba0d9d01de0ceb38ce17596bb28fe648/src/tox_ansible/plugin.py#L464

contains `--parents` which is not supported on MacOS. ~Changing to `-p` should solve it for all platforms.~ `-p` is not doing the same, so on MacOS ppl would have to install GNU `cp`.

Can you look into other alternatives to make this more portable?

Thanks

### PR DESCRIPTION
**Pull request by h3nryc0ding**
**Resolves #246**

### Summary
Replaced the use of `cp --parents` with bash scripting to ensure compatibility with macOS, avoiding the need to install the GNU version of `cp`.

### Details
To verify this change, I ran a minimal example using both `cp` and `rsync`:

- Test run with `cp` on `macos-latest` and `ubuntu-latest`: [GitHub Action run](https://github.com/h3nryc0ding/tox-ansible-repro/actions/runs/11115953425)
- Test run with `rsync` on `macos-latest` and `ubuntu-latest`: [GitHub Action run](https://github.com/h3nryc0ding/tox-ansible-repro/actions/runs/11115973446)

#### Note
The test setup intentionally causes all **integration tests to fail** while ensuring **unit tests succeed**. This confirms that the tests are executing correctly as expected.

### CODE REVIEW

**Comment by h3nryc0ding** [comment]
Hi @cidrblock , could you please provide feedback on this PR? I'm blocked until it's merged and would appreciate your input. Thanks in advance!

**Review by ssbarnea — CHANGES_REQUESTED** [review]
rsync is not installed by default on many OS-es so that is not the right way to address that bug report. Probably we want to use a pure python implementation instead to fix it.

**Comment by h3nryc0ding** [comment]
Thanks for the feedback. I changed to a bash scripting approach with standard Unix commands (`mkdir -p`, `cp`). It works but produces somewhat messy `stdout`. Any suggestions for improving the output formatting?

**Comment by h3nryc0ding** [comment]
Hi @abhikdps  @ssbarnea ,
Thanks for looking over my PR! I noticed the changes were copied directly to #391 rather than merging the PR itself, which made me a bit disappointed. Generally, it’s great to keep contributor history intact by merging or attributing changes, as it makes collaboration feel more valued.

**Comment by abhikdps** [comment]
> Hi @abhikdps  @ssbarnea ,
> 
> Thanks for looking over my PR! I noticed the changes were copied directly to #391 rather than merging the PR itself, which made me a bit disappointed. Generally, it’s great to keep contributor history intact by merging or attributing changes, as it makes collaboration feel more valued.

Hi @h3nryc0ding ,
We understand the value of your contribution. I wanted to make a little change in your PR itself. Unfortunately, I couldn't fetch your changes in my local system (I am not sure why) and hence decided to create a new PR. Thanks again for your contribution and sorry for your disappointment. Keep contributing!

**Pull request closed without merging**
